# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0dbe87b82e5d6e6af1ae019172e3f2d909c617c6ba9574cb6fe6496c6d56f41f62e5fad1e95450b66a74c93f4a9298325a7f46e1703f5feed77b9013fdde2a76

test:
  secret_key_base: 860eecd655485d74c3a4f00edfd9acc1986c8b46aee631234c2abcc5de31357faaba5ad34a16bc3ff3f3518d3752a2ee49cbee0c0714189b99a278f314f4bdca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
